name: Deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.6'
        bundler-cache: true

    - name: Fix Bundler and Gem issues
      run: |
        gem update --system
        gem install bundler
        bundle update --bundler
        bundle install

    - name: Install Dependencies
      run: npm install -g @mermaid-js/mermaid-cli

    - name: Setup Git config
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Define Branch Variables
      run: |
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV
          echo "NO_PUSH=--no-push" >> $GITHUB_ENV
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        fi
        echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_ENV

    - name: Check for uncommitted files
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          echo "❌ ERROR: Il y a des fichiers non commités !"
          git status
          exit 1
        fi

    - name: Deploy website
      run: bash bin/deploy --verbose --src ${{ env.SRC_BRANCH }} --deploy ${{ env.DEPLOY_BRANCH }} --force
